title: BISA 1
author: Tim VanRavenswaay
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Nothing to see here.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  tdv218 # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
